version: "3.9"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: ttalk-swagger-ui
    ports:
      - "9001:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
